/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    BackgroundBlinkingSquares: typeof import('./src/components/Background/BackgroundBlinkingSquares.vue')['default']
    BackgroundDandelions: typeof import('./src/components/Background/BackgroundDandelions.vue')['default']
    BackgroundMessagesAppear: typeof import('./src/components/Background/BackgroundMessagesAppear.vue')['default']
    ButtonBurger: typeof import('./src/components/Button/ButtonBurger.vue')['default']
    ButtonGithub: typeof import('./src/components/Button/ButtonGithub.vue')['default']
    ButtonImage: typeof import('./src/components/Button/ButtonImage.vue')['default']
    ButtonLinkedin: typeof import('./src/components/Button/ButtonLinkedin.vue')['default']
    ButtonNavigation: typeof import('./src/components/Button/ButtonNavigation.vue')['default']
    ButtonThemeChange: typeof import('./src/components/Button/ButtonThemeChange.vue')['default']
    ButtonThemeChange2: typeof import('./src/components/Button/ButtonThemeChange2.vue')['default']
    ContentDecorator: typeof import('./src/components/Wrapper/ContentDecorator.vue')['default']
    Dialog: typeof import('./src/components/Wrapper/Dialog.vue')['default']
    FrameWindow: typeof import('./src/components/Wrapper/FrameWindow.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCommunity: typeof import('./src/components/Icon/IconCommunity.vue')['default']
    IconGit: typeof import('./src/components/Icon/IconGit.vue')['default']
    IconGithub: typeof import('./src/components/Icon/IconGithub.vue')['default']
    IconLinkedin: typeof import('./src/components/Icon/IconLinkedin.vue')['default']
    IconSvg: typeof import('./src/components/Image/IconSvg.vue')['default']
    ImageDef: typeof import('./src/components/Image/ImageDef.vue')['default']
    ImageOverlay: typeof import('./src/components/Image/ImageOverlay.vue')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Modal: typeof import('./src/components/Wrapper/Modal.vue')['default']
    NotFound404: typeof import('./src/components/Errors/NotFound404.vue')['default']
    OverflowMenu: typeof import('./src/components/OverflowMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableContent: typeof import('./src/components/Wrapper/ScrollableContent.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    SocialButtons: typeof import('./src/components/Button/SocialButtons.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    WrapperText: typeof import('./src/components/Wrapper/WrapperText.vue')['default']
  }
}

// For TSX support
declare global {
  const AboutMe: typeof import('./src/components/AboutMe.vue')['default']
  const BackgroundBlinkingSquares: typeof import('./src/components/Background/BackgroundBlinkingSquares.vue')['default']
  const BackgroundDandelions: typeof import('./src/components/Background/BackgroundDandelions.vue')['default']
  const BackgroundMessagesAppear: typeof import('./src/components/Background/BackgroundMessagesAppear.vue')['default']
  const ButtonBurger: typeof import('./src/components/Button/ButtonBurger.vue')['default']
  const ButtonGithub: typeof import('./src/components/Button/ButtonGithub.vue')['default']
  const ButtonImage: typeof import('./src/components/Button/ButtonImage.vue')['default']
  const ButtonLinkedin: typeof import('./src/components/Button/ButtonLinkedin.vue')['default']
  const ButtonNavigation: typeof import('./src/components/Button/ButtonNavigation.vue')['default']
  const ButtonThemeChange: typeof import('./src/components/Button/ButtonThemeChange.vue')['default']
  const ButtonThemeChange2: typeof import('./src/components/Button/ButtonThemeChange2.vue')['default']
  const ContentDecorator: typeof import('./src/components/Wrapper/ContentDecorator.vue')['default']
  const Dialog: typeof import('./src/components/Wrapper/Dialog.vue')['default']
  const FrameWindow: typeof import('./src/components/Wrapper/FrameWindow.vue')['default']
  const Header: typeof import('./src/components/Header.vue')['default']
  const IconCommunity: typeof import('./src/components/Icon/IconCommunity.vue')['default']
  const IconGit: typeof import('./src/components/Icon/IconGit.vue')['default']
  const IconGithub: typeof import('./src/components/Icon/IconGithub.vue')['default']
  const IconLinkedin: typeof import('./src/components/Icon/IconLinkedin.vue')['default']
  const IconSvg: typeof import('./src/components/Image/IconSvg.vue')['default']
  const ImageDef: typeof import('./src/components/Image/ImageDef.vue')['default']
  const ImageOverlay: typeof import('./src/components/Image/ImageOverlay.vue')['default']
  const Introduction: typeof import('./src/components/Introduction.vue')['default']
  const Logo: typeof import('./src/components/Logo.vue')['default']
  const Modal: typeof import('./src/components/Wrapper/Modal.vue')['default']
  const NotFound404: typeof import('./src/components/Errors/NotFound404.vue')['default']
  const OverflowMenu: typeof import('./src/components/OverflowMenu.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScrollableContent: typeof import('./src/components/Wrapper/ScrollableContent.vue')['default']
  const Skills: typeof import('./src/components/Skills.vue')['default']
  const SocialButtons: typeof import('./src/components/Button/SocialButtons.vue')['default']
  const TopBar: typeof import('./src/components/TopBar.vue')['default']
  const WrapperText: typeof import('./src/components/Wrapper/WrapperText.vue')['default']
}